openapi: 3.0.3
info:
  title: wallapop search api
  description: |-
    API de consultas de wallapop, pillado por ingenieria inversa
  contact:
    email: gilmith@gmail.com
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: https://api.wallapop.com/api/v3
paths:
  /search:
    get:
      tags:
        - search
      summary: search productos
      description: Busqueda parametrizada en un get
      operationId: search
      parameters:
        - name: keywords
          in: query
          description: palabras claves a buscar
          required: true
          explode: true
          schema:
            type: string
        - name: start
          in: query
          description: pagina de busqueda
          required: false
          explode: true
          schema:
            type: integer
            default: 0
        - name: order_by
          in: query
          description: filtro de busqueda de distacia precio etc. Si eliges newest hay que poner una fecha de inicio ver 
          required: false
          explode: true
          schema:
            type: string
            enum:
              - "closed"
              - "price_high_to_low"
              - "price_low_to_high"
              - "most_relevance"
              - "newest"
            default: "closed"
        - name: pagination_date
          in: query
          description: dos meses menos la fecha actual con hora
          required: false
          explode: true
          schema:
            type: string
        - name: condition
          in: query
          description: condiciones del producto
          required: false
          explode: true
          schema:
            type: string
            enum:
              - "new"
              - "as_good_as_new"
              - "good"
              - "fair"
        - name: longitude
          in: query
          description: longitud de la ubicacion
          required: false
          explode: true
          schema:
            type: number
        - name: latitude
          in: query
          description: latitud de la ubicacion
          required: false
          explode: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search'   
  /user/${id}:
   get:
      tags:
        - user details
      summary: busqueda del usuario
      description: Busqueda por id de usuario
      operationId: users
      parameters:
        - name: id
          in: path
          description: id del usuario a buscar
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'   
  /user/${id}/items:
   get:
      tags:
        - productos a la venta por usuario
      summary: obtener todos los productos del usuario
      description: Busqueda por id de usuario y sus productos
      operationId: userItem
      parameters:
        - name: id
          in: path
          description: id del usuario a buscar
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userItem'
  /items/${id}:
    get:
      tags:
        - detalle de producto
      summary: detalles del producto
      description: devuelve los datelles del producto, fotos etc
      operationId: item
      parameters:
        - name: id
          in: path
          description: id del producto a obtener los detalles
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/item'
 
             
components:
  schemas:
    search:
      type: object
      properties:
        search_objects:
          type: array
          items:
            properties:
              id: 
                type: string
              title: 
                type: string
              description: 
                type: string
              distance: 
                type: number
              images:
                type: array
                items:
                  properties:
                    original:
                      type: string
                    xsmall:
                      type: string
                    small:
                      type: string
                    large:
                      type: string
                    medium: 
                      type: string
                    xlarge:
                      type: string
                    original_width:
                      type: string
                    original_height:
                      type: string
                
                user: 
                  type: object
                  properties:
                    id:
                      type: string
                    micro_name:
                      type: string
                    online:
                      type: boolean
                    kind: 
                      type: string
                    image:
                      type: object
                      properties:
                        original:
                          type: string
                        xsmall:
                          type: string
                        small:
                          type: string
                        medium:
                          type: string
                        large:
                          type: string
                        xlarge:
                          type: string
                        original_width:
                          type: number
                        original_height:
                          type: number
                flags:
                      type: object
                      properties:
                        pending:
                          type: boolean
                        sold:
                          type: boolean
                        reserved:
                          type: boolean
                        banned:
                          type: boolean
                        expired: 
                          type: boolean
                        onhold:
                          type: boolean
                visibility_flags:
                    type: object
                    properties:
                      bumped:
                        type: boolean
                      highlighted:
                        type: boolean
                      urgent:
                        type: boolean
                      country_bumped:
                        type: boolean
                      boosted:
                        type: boolean
                price:
                  type: number
                currency:
                  type: string
                free_shipping:
                  type: boolean
                web_slug:
                  type: string
                category_id:
                  type: number
                shipping:
                  type: object
                  properties:
                    item_is_shippable: 
                      type: boolean
                    user_allows_shipping:
                      type: boolean
                supports_shipping:
                  type: boolean
                shipping_allowed:
                  type: boolean
                seller_id:
                  type: string
                favorited: 
                  type: boolean
                modification_date:
                  type: number
                location:
                  type: object
                  properties:
                    city:
                      type: string
                    postal_code:
                      type: string
                    country_code:
                      type: string
                from:
                  type: number
                to: 
                  type: number
                distance_order:
                  type: boolean
                keywords:
                  type: string
                order:
                  type: string
                  enum:
                    - "closed"
                    - "price_high_to_low"
                    - "price_low_to_high"
                    - "most_relevance"
                    - "newest"
                bubble: 
                  type: string
                search_point:
                  type: object
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
    user:
      type: object
      properties:
        id:
          type: string
        micro_name: 
          type: string
        type:
          type: string
        image:
          type: object
          properties:
            id: 
              type: string
            original_width:
              type: number
            original_height:
              type: number
            averrage_hex_box:
              type: string
            urls_by_size:
              type: object
              properties:
                small: 
                  type: string
                xsmall:
                  type: string
                original:
                  type: string
                large:
                  type: string
                xlarge:
                  type: string
                medium:
                  type: string
        location:
          type: object
          properties:
            approximated_latitude:
              type: number
            approximated_longitude:
              type: number
            city:
              type: string
            zip:
              type: string
            country_code:
              type: string
            approxRadius:
              type: string
            approximated_location: 
              type: boolean
        gender:
          type: string
        web_slug:
          type: string
        url_share:
          type: string
        register_date:
          type: string
        featured:
          type: boolean
    userItem:
      type: object
      properties:
        data:
          type: array
          items:
            properties:
              id:
                type: string
              title:
                type: string
              description:
                type: string
              category_id:
                type: string
              images:
                type: array
                items:
                  properties:
                    id: 
                      type: string
                    average_color:
                      type: string
                    urls:
                      type: object
                      properties:
                        small:
                          type: string
                        medium:
                          type: string
                        big:
                          type: string
              price:
                type: object
                properties:
                  aumount: 
                    type: number
                  currency:
                    type: number
              type_attributes:
                type: object
                properties:
                  condition:
                    type: object
                    properties:
                      value:
                        type: string 
                      title:
                        type: string
                      text:
                        type: string
                      icon_text:
                        type: string
                  up_to_kg:
                    type: object
                    properties:
                      value:
                        type: string
                      title:
                        type: string
                      text:
                        type: string
                      icon_text:
                        type: string
              shipping:
                type: object
                properties:
                  item_is_shippable:
                    type: boolean
                  user_allows_shipping:
                    type: boolean
        meta:
          type: object
          properties:
            next:
              type: string
    item:
      type: object
      properties:
        id:
          type: string
        title:
          type: object
          properties:
            original: 
              type: string
        description:
          type: object
          properties:
            original:
              type: string
        taxonomy:
          type: array
          items:
            properties:
              id:
                type: number
              name:
                type: string
              icon:
                type: string
        type:
          type: string
        user:
          type: object
          properties:
            id: 
              type: string
        slug:
          type: string
        share_url:
          type: string
        modified_date:
          type: string
        images:
          type: array
          items:
            properties:
              id: 
                type: string
              average_color:
                type: string
              urls:
                type: object
                properties:
                  small:
                    type: string
                  medium:
                    type: string
                  big:
                    type: string
        price:
          type: object
          properties:
            aumount: 
              type: number
            currency:
              type: number
            type_attributes:
              type: object
              properties:
                condition:
                  type: object
                  properties:
                    value:
                      type: string 
                    title:
                      type: string
                    text:
                      type: string
                    icon_text:
                      type: string
                up_to_kg:
                  type: object
                  properties:
                    value:
                      type: string
                    title:
                      type: string
                    text:
                      type: string
                    icon_text:
                      type: string
            shipping:
              type: object
              properties:
                item_is_shippable:
                  type: boolean
                user_allows_shipping:
                  type: boolean
            supports_shipping:
              type: object
              properties:
                flag:
                  type: boolean
            hashtags:
              type: object
              properties:
                values:
                  type: array
                  items:
                  properties:
                  

              
                  
                
        
        
                
                        
                
      
