CREATE TABLE IF NOT EXISTS  TERMINOS (
ID NUMBER PRIMARY KEY,
TERMINO VARCHAR2(32500));

CREATE TABLE IF NOT EXISTS  PRODUCTO(
ID VARCHAR2(300) PRIMARY KEY,
USERID VARCHAR2(300),
TITLE VARCHAR2(32500),
ULTIMA_MODIFICACION TIMESTAMP,
PRECIO NUMBER,
LOCALIZACION VARCHAR2(32500),
SLUG VARCHAR(32500),
CONDICIONES NUMBER,
DESCRIPTION CLOB);

CREATE TABLE  IF NOT EXISTS TERMINO_PRODUCTO(
IDTERMINO NUMBER,
IDPRODUCTO VARCHAR2(300),
FOREIGN  KEY (IDTERMINO) REFERENCES TERMINOS(ID),
FOREIGN  KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID));

CREATE TABLE IF NOT EXISTS CONDICIONES( 
ID NUMBER PRIMARY KEY,
CONDICION VARCHAR2(300));

CREATE TABLE IF NOT EXISTS PRODUCTO_CONDICIONES( 
IDPRODUCTO VARCHAR2 (300),
IDCONDICION NUMBER);

CREATE TABLE IF NOT EXISTS ESTADO (
ID NUMBER,
ESTADO VARCHAR2(300));

CREATE TABLE IF NOT EXISTS PRODUCTO_ESTADO(
IDPRODUCTO VARCHAR2(300),
IDESTADO NUMBER);

CREATE TABLE IF NOT EXISTS IMAGENES(
ID VARCHAR2(300),
URL VARHCAR2(32500),
IMAGENV BLOB);

CREATE TABLE IF NOT EXISTS PRODUCTO_IMAGEN(
IDPRODUCTO VARCHAR2(300),
IDIMAGEN VARCHAR2(300));

CREATE TABLE IF NOT EXISTS VENDEDOR( 
ID VARCHAR2(300),
NICK VARCHAR2(300),
SLUG VARCHAR2(300),
ENVENTA NUMBER, 
VENDIDOS NUMBER,
SCORE NUMBER);

CREATE TABLE IF NOT EXISTS VENDEDOR_PRODUCTO( 
IDVENDEDOR VARCHAR2(300),
IDPRODUCTO VARCHAR2(300));

CREATE TABLE IF NOT EXISTS OPINIONES( 
ID VARCHAR2(300),
DESCRIPTION CLOB,
FECHA TIMESTAMP);

CREATE TABLE IF NOT EXISTS OPINION_PRODUCTO(
IDOPINION VARCHAR2(300),
IDPRODUCTO VARHCAR2(300));

CREATE TABLE IF NOT EXISTS  OPINION_VENDEDOR(
IDOPINION VARCHaR2(300),
IDVENDEDOR VARCHAR2(300);

CREATE TABLE IF NOT EXISTS  PROCESSED(
ID NUMBER,
FECHA TIMESTAMP,
SCORE NUMBER,
COMENTARIOS CLOB);


CREATE TABLE IF NOT EXISTS PRODUCTO_PROCESADO(
IDPRODUCTO VARCHAR2(300),
IDPROCESO NUMBER);

CREATE SEQUENCE IF NOT EXISTS SEQ_TERMINO START WITH 1 NOMAXVALUE CACHE 20;
CREATE SEQUENCE IF NOT EXISTS SEQ_PROCESO START WITH 1 NOMAXVALUE CACHE 20;

