CREATE TABLE IF NOT EXISTS  TERMINOS (
ID NUMBER PRIMARY KEY,
TERMINO VARCHAR2(32500));

CREATE TABLE IF NOT EXISTS  PRODUCTO(
ID VARCHAR2(300) PRIMARY KEY,
USERID VARCHAR2(300),
TITLE VARCHAR2(32500),
ULTIMA_MODIFICACION TIMESTAMP,
PRECIO NUMBER,
LOCALIZACION VARCHAR2(32500),
SLUG VARCHAR(32500),
CONDICIONES NUMBER,
DESCRIPTION CLOB);

CREATE TABLE  IF NOT EXISTS TERMINO_PRODUCTO(
IDTERMINO NUMBER,
IDPRODUCTO VARCHAR2(300),
FOREIGN  KEY (IDTERMINO) REFERENCES TERMINOS(ID),
FOREIGN  KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID));

CREATE TABLE IF NOT EXISTS CONDICIONES( 
ID NUMBER PRIMARY KEY,
CONDICION VARCHAR2(300));


CREATE TABLE IF NOT EXISTS ESTADO (
ID NUMBER,
ESTADO VARCHAR2(300));


CREATE TABLE IF NOT EXISTS IMAGENES(
ID VARCHAR2(300),
URL VARHCAR2(32500),
IMAGENV BLOB);


CREATE TABLE IF NOT EXISTS VENDEDOR( 
ID VARCHAR2(300),
NICK VARCHAR2(300),
SLUG VARCHAR2(300),
ENVENTA NUMBER, 
VENDIDOS NUMBER,
SCORE NUMBER);



CREATE TABLE IF NOT EXISTS OPINIONES( 
ID VARCHAR2(300),
DESCRIPTION CLOB,
FECHA TIMESTAMP);





CREATE TABLE IF NOT EXISTS  PROCESSED(
ID NUMBER,
FECHA TIMESTAMP,
SCORE NUMBER,
COMENTARIOS CLOB);


drop table producto_condiciones;


CREATE TABLE PRODUCTO_CONDICIONES (
		IDPRODUCTO VARCHAR2(300),
		IDCONDICION DECIMAL(65535 , 32767),
                FOREIGN KEY (IDPRODUCTO ) REFERENCES PRODUCTO(ID),
FOREIGN KEY (IDCONDICION) REFERENCES CONDICIONES(ID)
	);

drop table producto_estado;

CREATE TABLE IF NOT EXISTS PRODUCTO_ESTADO(
IDPRODUCTO VARCHAR2(300),
IDESTADO NUMBER,
FOREIGN KEY (IDPRODUCTO ) REFERENCES PRODUCTO(ID),
FOREIGN KEY (IDESTADO) REFERENCES ESTADO(ID)
);

DROP TABLE PRODUCTO_IMAGEN;

CREATE TABLE IMAGEN(
IDPRODUCTO VARCHAR2(300),
URL VARCHAR2(32000),
IMAGEN BLOB,
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID) );

DROP TABLE VENDEDOR_PRODUCTO;

CREATE TABLE IF NOT EXISTS VENDEDOR_PRODUCTO( 
IDVENDEDOR VARCHAR2(300),
IDPRODUCTO VARCHAR2(300),
FOREIGN KEY (IDVENDEDOR ) REFERENCES VENDEDOR(ID),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID) );

DROP TABLE TERMINO_PRODUCTO;

CREATE TABLE  IF NOT EXISTS TERMINO_PRODUCTO(
IDTERMINO NUMBER,
IDPRODUCTO VARCHAR2(300),
FOREIGN  KEY (IDTERMINO) REFERENCES TERMINOS(ID),
FOREIGN  KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID));

CREATE TABLE  IF NOT EXISTS VENDEDOR_OPINIONES(
IDVENDEDOR VARCHAR2(300),
IDOPINION VARCHAR2(300),
FOREIGN  KEY (IDVENDEDOR) REFERENCES VENDEDOR(ID),
FOREIGN KEY (IDOPINION) REFERENCES OPINIONES(ID));

DROP TABLE PRODUCTO_PROCESADO;

CREATE TABLE IF NOT EXISTS PRODUCTO_PROCESADO(
IDPRODUCTO VARCHAR2(300),
IDPROCESO NUMBER, 
FOREIGN KEY (IDPROCESO) REFERENCES PROCESSED(ID),
FOREIGN KEY(IDPRODUCTO) REFERENCES PRODUCTO(ID));
CREATE SEQUENCE IF NOT EXISTS SEQ_TERMINO START WITH 1 NOMAXVALUE CACHE 20;
CREATE SEQUENCE IF NOT EXISTS SEQ_PROCESO START WITH 1 NOMAXVALUE CACHE 20;

